Repository traas-stack/kapacity, pull requests merged in 2023-07, with the labels that each got.

#41 HorizontalPortrait: Support Kubernetes CronJob as external horizontal portrait algorithm job
  pkg/portrait/algorithm/externaljob/jobcontroller/cronjob.go
  pkg/portrait/algorithm/externaljob/jobcontroller/cronjob_test.go
  pkg/util/common.go
Labels: kind/feature

#44 Use SSA (Server-Side Apply) in Makefile
  Makefile
Labels: kind/bug

#45 Add unit tests for util/common.go file
  pkg/util/common_test.go
Labels: kind/test

#46 Introduce complete metric query support to Prometheus metric provider
  config/manager/config.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  go.mod
  go.sum
  main.go
  pkg/metric/labels.go
  pkg/metric/provider/metricsapi/provider.go
  pkg/metric/provider/prometheus/external_series_registry.go
  pkg/metric/provider/prometheus/metrics_config.go
  pkg/metric/provider/prometheus/object_series_registry.go
  pkg/metric/provider/prometheus/provider.go
  pkg/metric/provider/prometheus/provider_test.go
  pkg/metric/provider/prometheus/query.go
  pkg/metric/provider/prometheus/resource.go
  pkg/metric/provider/prometheus/runnable.go
  pkg/metric/query.go
  pkg/metric/value.go
  pkg/portrait/generator/reactive/metrics.go
  pkg/util/template.go
  pkg/util/wait.go
  pkg/util/wait_test.go
Labels: kind/feature, kind/dependencies

#48 Remove redundant examples dir
  examples/autoscaling/cron-portrait-sample.yaml
  examples/autoscaling/dynamic-portrait-reactive-sample.yaml
  examples/autoscaling/static-portrait-sample.yaml
  examples/kapacity-deploy.yaml
  examples/metrics-server.yaml
  examples/nginx-deployment.yaml
  examples/nginx-statefulset.yaml
Labels: kind/cleanup
