Repository traas-stack/kapacity, pull requests merged in 2023-09, with the labels that each got.

#52 Enhancements of prometheus metric provider: query range sharding & more client configs
  config/manager/manager.yaml
  main.go
  pkg/metric/provider/metricsapi/provider.go
  pkg/metric/provider/prometheus/provider.go
  pkg/metric/provider/prometheus/runnable.go
  pkg/metric/value.go
  pkg/portrait/generator/reactive/metrics.go
Labels: kind/feature

#43 Expose the unified metric provider interface as a service
  go.mod
  main.go
  pkg/metric/service/api/metric.pb.go
  pkg/metric/service/api/metric.proto
  pkg/metric/service/api/provider.pb.go
  pkg/metric/service/api/provider.proto
  pkg/metric/service/api/provider_grpc.pb.go
  pkg/metric/service/server.go
  pkg/util/common.go
  pkg/util/common_test.go
Labels: kind/feature, kind/api-change, kind/dependencies

#53 chore: simplify referral license
  pkg/metric/provider/metricsapi/provider.go
  pkg/metric/provider/prometheus/external_series_registry.go
  pkg/metric/provider/prometheus/object_series_registry.go
  pkg/metric/provider/prometheus/resource.go
  pkg/metric/provider/prometheus/runnable.go
  pkg/pod/sorter/active_pods_with_ranks.go
  pkg/pod/sorter/active_pods_with_ranks_test.go
  pkg/portrait/generator/reactive/metrics.go
  pkg/portrait/generator/reactive/replica_calculator.go
  pkg/scale/scaler.go
  pkg/util/apimachinery.go
  pkg/util/pod.go
  pkg/util/wait.go
  pkg/util/wait_test.go
  pkg/workload/replicaset.go
Labels: kind/cleanup

#54 HorizontalPortrait: Introduce fully functional k8s HPA reactive scaling
  go.mod
  go.sum
  main.go
  pkg/portrait/generator/reactive/generator.go
  pkg/portrait/generator/reactive/generator_test.go
  pkg/portrait/generator/reactive/metrics.go
  pkg/portrait/generator/reactive/metrics_client.go
  pkg/portrait/generator/reactive/metrics_client_test.go
  pkg/portrait/generator/reactive/replica_calculator.go
  pkg/util/client.go
  pkg/util/client_test.go
Labels: kind/feature, kind/dependencies

#55 Utilize k8s code dep to reduce code dup
  controllers/autoscaling/replicaprofile_controller.go
  pkg/pod/sorter/active_pods_with_ranks.go
  pkg/pod/sorter/active_pods_with_ranks_test.go
  pkg/pod/traffic/readinessgate.go
  pkg/util/apimachinery.go
  pkg/util/apimachinery_test.go
  pkg/util/pod.go
  pkg/util/pod_test.go
  pkg/util/wait_test.go
  pkg/workload/replicaset.go
Labels: kind/cleanup

#56 Introduce workload external metric query with prom provider support
  pkg/metric/provider/prometheus/query.go
  pkg/metric/query.go
  pkg/metric/service/api/metric.pb.go
  pkg/metric/service/api/metric.proto
  pkg/metric/service/server.go
Labels: kind/feature, kind/api-change

#58 HorizontalPortrait: Introduce ConfigMap horizontal result fetcher
  controllers/autoscaling/horizontalportrait_controller.go
  controllers/autoscaling/intelligenthorizontalpodautoscaler_controller.go
  main.go
  pkg/portrait/algorithm/externaljob/resultfetcher/configmap.go
  pkg/portrait/algorithm/externaljob/resultfetcher/configmap_test.go
  pkg/portrait/algorithm/externaljob/resultfetcher/interfaces.go
Labels: kind/feature

#59 Introduce object selector to restrict controller list watch
  main.go
Labels: kind/feature

#60 Update manifests
  config/manager/config.yaml
  config/rbac/role.yaml
  controllers/autoscaling/horizontalportrait_controller.go
Labels: kind/feature

#63 Algo: Introduce replicas prediction job
  algorithm/kapacity/portrait/horizontal/predictive/main.py
Labels: kind/feature, kind/algorithm
